# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 20:02
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, unique=True)),
                ('job_vacancy', models.CharField(max_length=100)),
                ('job_description', ckeditor.fields.RichTextField()),
                ('job_post_date', models.DateField()),
                ('job_qualification', models.CharField(max_length=100, null=True)),
                ('job_post', models.CharField(max_length=100, null=True)),
                ('job_last_date', models.DateField()),
                ('slug', models.CharField(max_length=150)),
                ('job_logo', models.ImageField(blank=True, null=True, upload_to='logo_pics/%Y-%m-%d/', verbose_name='Logo')),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='job_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.JobCategory'),
        ),
    ]
